--- 
title: "Статистика чрез R"
subtitle: "Ръководство"
author: "Борис Велков"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Ръководството за статистици, иконометрици и анализатори при работата с R."
---

```{r setup, include=FALSE}
# options(
#   htmltools.dir.version = FALSE, formatR.indent = 2,
#   width = 65, digits = 4, warnPartialMatchAttr = FALSE, warnPartialMatchDollar = FALSE
# )
```

# Въведение {#intro} 

Целта на това ръководство е да бъде в помощ на статистици, иконометрици и анализатори при работата с R. То представя полезни техники за събиране, представяне и разпространение на статистически данни и няма за цел да запознае читателя с основите, синтаксиса или структурите на езика. В Интернет  могат да се намерят много материали за начинаещи, като добър старт дават например страницата [Learn R](https://support.rstudio.com/hc/en-us/categories/200098757-Learn-R){target="_blank"} на Rstudio или книгата  _Mastering Software Development in R_ [@Peng2017].

Примерите разглеждани в ръководството са разработени, стартирани и изпълнени на потребителската машина с  [R](https://cran.r-project.org/){target="_blank"} версия 4.0.3 и [RStudio](https://rstudio.com/products/rstudio/){target="_blank"} версия 1.3. 
За голяма част от използваните в ръководството примери инсталирането на RStudio не е необходимо и би могло да се изпълнят, без инсталирането интегрираната среда за разработка. Поради  интеграция на средата с част от използваните в примерите пакети, инсталирането на средата е препоръчително и би улеснила създаването и изпълнението на кода.

<!-- Пакетите използвани в примерите. -->
<!-- [@R-base] -->



